###
POST http://localhost:4004/odata/v4/test-portal-am/mjicdnmodicncdcc
Content-Type: application/json
 
# {
#   "D4OXYPALUYAIDNSO": "{\"INJID\":3,\"EMPID\":\"SLS1380\",\"EMPNM\":\"Piyush Zagade\",\"SUPVR\":\"NIDHI\",\"TPHNE\":\"3453452345\",\"CLSSF\":\"Injury\",\"LDWRK\":\"2025-10-07\",\"FDABS\":\"2025-11-08\",\"OCCIL\":\"Y\",\"RTWRK\":\"Y\",\"RGTIM\":\"2025-11-07T10:30:00Z\",\"NAINC\":\"Near Miss\",\"CAUSE\":\"Slippery Floor\"}"
# }
{
  "A23EMOI12NM34ML1": "{\"BDPID\":0,\"EMPID\":\"SLS1382\",\"BDYPT\":\"Right\",\"NOINJ\":\"top\",\"SIDE_\":\"top\",\"BPDES\":\"head\"}"
}
